name: lilas_kokoro
description: A kawaii companion app with reminders, alarms, and more.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add this line if it's not already there
  device_info_plus: ^9.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  path_provider: ^2.1.0
  file_picker: ^9.2.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.4.0
  # Add skeletonizer package
  skeletonizer: ^1.0.1
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3
  uuid: ^4.5.1
  path: ^1.8.3
  # Added for audio playback
  audio_session: ^0.1.18
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  # Add for API secure storage
  envied: ^0.5.3
  # Add http for API calls
  http: ^1.2.1
  # Add image_picker for profile picture
  image_picker: ^1.0.7
  persistent_bottom_nav_bar: ^6.2.1
  package_info_plus: ^8.3.0
  go_router: ^15.1.1
  simple_animations: ^5.1.0
  flutter_animate: ^4.5.2
  url_launcher: ^6.2.4
  # Add generative art backgrounds package
  gen_art_bg: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Add build_runner and envied_generator
  build_runner: ^2.4.7
  envied_generator: ^0.5.3
  # Add flutter_launcher_icons for custom app icon
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/images/onboarding/
    - assets/fonts/
    # Removed .env from assets

  # Declare fonts to prevent flickering
  fonts:
    - family: Barriecito
      fonts:
        - asset: assets/fonts/Barriecito-Regular.ttf

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/App-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/App-icon.png"
  web:
    generate: true
    image_path: "assets/images/App-icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/App-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/App-icon.png"
